### ISSUE TITLE
csv: add interpolation

### ISSUE THREAD

**Issue by gyuho** [coreos/dbtester#216]
When vendor has this patch https://github.com/gyuho/psn/pull/27

Raw data will be without interpolation.
Now dbtester needs some kind of interpolation to handle missing timestamps in system metrics.

**Comment by heyitsanthony** [comment]
Going to add finer-grained time stamps. That way it won't "miss" anything, just the time series won't be evenly spaced.

**Comment by heyitsanthony** [comment]
(this will be a problem for values that are computed by deltas, of course; if the spacing is different then a flat-line on evenly spaced intervals will look choppy when plotted with irregular spacing)
