### ISSUE TITLE
handle missing timestamps in monitor data

### ISSUE THREAD

**Issue by gyuho** [coreos/dbtester#26]
CPU and memory monitoring records usage for every-second, but
sometimes there could be some gaps of a few seconds where data
did not get collected. This causes a problem when aggregating with
benchmark data which also fills in missing timestamps.

We need a way to fill in these empty rows with estimates.

**Comment by xiang90** [comment]
@gyuho We probably do not need to actually. The plotting tool will do it for your as long as the time points is still correct. But for calculation purpose, we need to be careful.

**Comment by gyuho** [comment]
@xiang90 Ok, I will play with plotting tools to see if we can cover these cases. Thanks!
