### ISSUE TITLE
Experiment with eBPF

### ISSUE THREAD

**Issue by gyuho** [coreos/dbtester#304]
eBPF to get various system metrics

- http://www.brendangregg.com/blog/2015-05-15/ebpf-one-small-step.html
- http://www.brendangregg.com/ebpf.html

**Comment by pmoust** [comment]
@gyuho did you use BPF-collected metrics afterall?

**Comment by gyuho** [comment]
Had no bandwidth to try it out. Will revisit in the future. Thanks!
