### ISSUE TITLE
Sizing ZooKeeper's JVM's heap

### ISSUE THREAD

**Issue by alexbrasetvik** [coreos/dbtester#307]
It looks like you're not configuring the Java heap explicitly.

At least some of the high variance in latency and particularly high CPU-usage might stem from excessive GCs.

I'd look into what heap size you're running with and what the performance look like if you tune it, and state the heap size where you mention the JVM version, etc.

I've got some experience with ZK's heap not being right :) https://www.elastic.co/blog/elastic-cloud-outage-april-2016

Thanks for thoroughly testing this! :)

**Comment by gyuho** [comment]
We won't disadvantage Zookeeper by giving less heap than needed, but agree it should be configurable. I will make it configurable next week. Thanks.

**Comment by gyuho** [comment]
Closing via https://github.com/coreos/dbtester/pull/308.
Will close https://github.com/coreos/dbtester/issues/309 when the new test results are ready.
