### ISSUE TITLE
Is support add another db system?

### ISSUE THREAD

**Issue by suteng** [coreos/dbtester#314]
Perfect test framework.
Is this support t add another db system?
Is there an user guide?

Thanks.

**Comment by gyuho** [comment]
Unlikely for now. We already support 5 databases (Zookeeper, etcd, Consul, cetcd, zetcd), which is already a lot to maintain. Regarding user guides, the closest thing that I have is sample config and script here https://github.com/coreos/dbtester/tree/master/test-configs.

Please let me know if you have more questions.
Thanks.
